// AUTO-GENERATED by scripts/snapshot-example.mjs — do not edit by hand.
import type { ExampleCase } from "./types";
import pediatricVaccineHesitancyCounseling from "./pediatric-vaccine-hesitancy-counseling";

const examples: ExampleCase[] = [
  pediatricVaccineHesitancyCounseling,
];

export function getAllExamples(): ExampleCase[] {
  return examples;
}

export function getExampleBySlug(slug: string): ExampleCase | undefined {
  return examples.find((e) => e.slug === slug);
}
