// AUTO-GENERATED by scripts/snapshot-example.mjs — do not edit by hand.
import type { ExampleCase } from "./types";
import addressingHydroxyureaNonadherenceAndMedicalMistrust from "./addressing-hydroxyurea-nonadherence-and-medical-mistrust";
import deliveringANewLeukemiaDiagnosisToAFamilyInTheEmergencyDepartment from "./delivering-a-new-leukemia-diagnosis-to-a-family-in-the-emergency-department";
import pediatricVaccineHesitancyCounseling from "./pediatric-vaccine-hesitancy-counseling";

const examples: ExampleCase[] = [
  addressingHydroxyureaNonadherenceAndMedicalMistrust,
  deliveringANewLeukemiaDiagnosisToAFamilyInTheEmergencyDepartment,
  pediatricVaccineHesitancyCounseling,
];

export function getAllExamples(): ExampleCase[] {
  return examples;
}

export function getExampleBySlug(slug: string): ExampleCase | undefined {
  return examples.find((e) => e.slug === slug);
}
